Add calls to create and delete required Dynamo tables
twitchscience/kinsumer pull request #14
Opened 2018-07-31 14:29 UTC by brentnd

Similar to [KCL](https://docs.aws.amazon.com/streams/latest/dev/kinesis-record-processor-ddb.html), kinsumer should provide the ability for the internal dynamo tables (`_clients`, `_checkpoints`, `_metadata`) to be created programmatically.

The new calls on `kinsumer` are `CreateRequiredTables()` and `DeleteTables()` which are opt-in so no existing functionality is changed.

No test functionality was changed but the new methods allowed a lot of existing test setup/cleanup code to be removed by using the new methods.

2018-07-31 14:36 UTC, brentnd commented
Looking at the build failures. Ran `golint` but checking `gometalinter` now.

2018-07-31 14:43 UTC, brentnd commented
I'm seeing these errors with and without my changes. Is it possible that `gometalinter` updates since the last build in May are now showing this as an issue?
`statsd/statsd.go:37::warning: Errors unhandled.,LOW,HIGH (gosec)
statsd/statsd.go:45::warning: Errors unhandled.,LOW,HIGH (gosec)
statsd/statsd.go:46::warning: Errors unhandled.,LOW,HIGH (gosec)
statsd/statsd.go:47::warning: Errors unhandled.,LOW,HIGH (gosec)
statsd/statsd.go:48::warning: Errors unhandled.,LOW,HIGH (gosec)
statsd/statsd.go:54::warning: Errors unhandled.,LOW,HIGH (gosec)
statsd/statsd.go:55::warning: Errors unhandled.,LOW,HIGH (gosec)`

The linting does pass when using `gometalinter.v2`.

2018-07-31 14:53 UTC, brentnd commented
https://github.com/alecthomas/gometalinter/pull/505 in gometalinter renamed `gas` to `gosec` so the `.travis.yml` file needed to be updated to disabled it by the new name.

2018-07-31 21:36 UTC, GarethLewin commented
FWIW the reason we didn't want to auto create the tables were so that people could setup alarms and the like. Reading code now.

2018-07-31 21:40 UTC, garethlewin requested changes
Create work, thanks for this. I have a few questions in the review.

2018-07-31 21:40 UTC, GarethLewin commented on config.go
> +func (c Config) WithDynamoCapacity(readCapacity, writeCapacity int64) Config {
Would you mind breaking this out into two separate with calls please?

2018-07-31 21:40 UTC, GarethLewin commented on kinsumer.go
> +func (k *Kinsumer) dynamoCreateTable(name, distKey string) error {
aws-sdk-go has `waiters` (https://github.com/aws/aws-sdk-go/blob/master/service/dynamodb/waiters.go) that are a reliable way to know if the create worked or failed. Thoughts on adding these waiters to `dynamoCreateTable` and `dynamoDeleteTable` Alternatively to `CreateRequiredTables` ?

2018-07-31 21:40 UTC, GarethLewin commented on kinsumer.go
> +func (k *Kinsumer) CreateRequiredTables() error {
Thoughts on running these in go routines with errgroup? That would build the tables faster.

2018-08-01 00:59 UTC, brentnd commented
I'll take a look at the comments and incorporate the requested changes tomorrow.

2018-08-01 13:24 UTC, brentnd commented on kinsumer.go
> +func (k *Kinsumer) CreateRequiredTables() error {
Done. Especially important now given the `waiter` in each create table call.

2018-08-01 13:24 UTC, brentnd commented on config.go
> +func (c Config) WithDynamoCapacity(readCapacity, writeCapacity int64) Config {
Done.

2018-08-01 13:24 UTC, brentnd commented on kinsumer.go
> +func (k *Kinsumer) dynamoCreateTable(name, distKey string) error {
Done.

2018-08-01 13:33 UTC, brentnd commented
Missed the new dependency on sync/errgroup.

2018-08-01 16:40 UTC, brentnd commented
All of the change requests have been addressed.

2018-08-03 05:02 UTC, GarethLewin commented
@brentnd did you forget to push your changes? I do not see any new commits.

2018-08-03 12:39 UTC, brentnd commented
I amended the original commit and force pushed.

2018-08-14 02:00 UTC, brentnd commented
@GarethLewin  Any updates on this?

2018-08-14 15:55 UTC, GarethLewin commented
Sorry was away all of last week.

2018-08-14 15:56 UTC, garethlewin approved these changes

2018-08-14 15:56 UTC, merged

2018-08-14 15:57 UTC, GarethLewin commented
Just as a general comment, please next time don't force push over your changes, makes PRs much harder to read.

2018-08-14 16:30 UTC, brentnd commented
Thanks @GarethLewin. Makes sense about the force push.